[package]
name = 'rhodcca'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'rhodcca'

[dependencies]
extendr-api = '0.8.1'
nalgebra = "0.33.2"

[profile.release]
lto = true
codegen-units = 1
