# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rhodcca_wrappers", use_symbols = TRUE, package_name = "rhodcca")

#' @usage NULL
#' @useDynLib rhodcca, .registration = TRUE
NULL

#' Detrended Covariance
#' Wrapper function for the rust function for doing the detrending.
#' @param x numeric vector.
#' @param y numeric vector.
#' @param m polinimial order for detrending (ex: 1=linear).
#' @return vector with the sum of squared residuals.
#'@export
detrend_cov <- function(x, y, m) .Call(wrap__detrend_cov, x, y, m)

#' Detrended Cross-Correlation Analysis
#' @param x Vetor numérico (série temporal).
#' @param y Vetor numérico (série temporal).
#' @param order Ordem do polinômio para detrending (ex: 1=linear).
#' @param scales Vetor de inteiros com as escalas para o cálculo.
#' @return Uma lista com `scales` e os coeficientes `rho`.
#' @export
dcca <- function(x, y, order, scales) .Call(wrap__dcca, x, y, order, scales)

#' Create logarithmically spaced scales.
#'
#' This generates a vector of scales starting from `scale_min`, where each
#' subsequent scale is the previous one multiplied by `scale_ratio`.
#' The process stops once `scale_max` is exceeded.
#'
#' # Arguments
#' * `scale_min` - An integer indicating the minimum scale to be resolved.
#' * `scale_max` - An integer indicating the maximum scale to be resolved.
#' * `scale_ratio` - A float indicating the ratio for successive scales.
#'
#' # Returns
#' A `Vec<i32>` of logarithmically spaced scales, sorted and unique.
#'
#' # Examples
#' // This would be called from R like so:
#' // scales <- logscale(scale_min = 16, scale_max = 1024, scale_ratio = 2)
#' @export
logscale <- function(scale_min, scale_max, scale_ratio) .Call(wrap__logscale, scale_min, scale_max, scale_ratio)

#' @export
iafft <- function() invisible(.Call(wrap__iafft))


# nolint end
